ProyectoSMP/Controllers/MantenimientoDeMaquinasController.cs
using ProyectoSMP.Models;
using Rotativa;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace ProyectoSMP.Controllers
{
    [Authorize]
    public class MantenimientoDeMaquinasController : Controller
    {

        private SMPEntities db = new SMPEntities();

        // GET: MantenimientoDeMaquinas
        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            if (TempData["Message"] != null)
            {
                ViewBag.Message = TempData["Message"].ToString();
            }
            var mantenimientoDeMaquina = db.Mantenimiento.Include(m => m.InventarioDeRepuestos).Include(m => m.Maquina).Include(m => m.Rol);
            return View(mantenimientoDeMaquina.ToList());
        }
        [Authorize(Roles = "Admin")]
        public FileResult Descargar(int? id)
        {

            Mantenimiento mantenimientoDeMaquina = db.Mantenimiento.Find(id);
            var ruta = mantenimientoDeMaquina.URLArchivo;
            return File(ruta, ruta);

        }
        public ActionResult Report()
        {

            return View(db.Mantenimiento.Include(m => m.InventarioDeRepuestos).Include(m => m.Maquina).Include(m => m.Rol));
        }
        public ActionResult Print()
        {
            return new ActionAsPdf("Report")
            { FileName = "Test.pdf" };
        }
        // GET: MantenimientoDeMaquinas/Details/5
        [Authorize(Roles = "Admin")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Mantenimiento mantenimientoDeMaquina = db.Mantenimiento.Find(id);
            if (mantenimientoDeMaquina == null)
            {
                return HttpNotFound();
            }
            return View(mantenimientoDeMaquina);
        }

        // GET: MantenimientoDeMaquinas/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            try
            {
                ViewBag.IdRepuesto = new SelectList(db.InventarioDeRepuestos, "IdRepuesto", "Nombre");
                ViewBag.IdMaquina = new SelectList(db.Maquina, "IdMaquina", "NombreMaquina");
                ViewBag.IdRol = new SelectList(db.Rol, "IdRol", "Descripcion");
                return View();
            }
            catch
            {
            ViewBag.IdRepuesto = new SelectList(db.InventarioDeRepuestos, "IdRepuesto", "Nombre");
            ViewBag.IdMaquina = new SelectList(db.Maquina, "IdMaquina", "NombreMaquina");
            ViewBag.IdRol = new SelectList(db.Rol, "IdRol", "Descripcion");
            return View();
            }
            
        }

        // POST: MantenimientoDeMaquinas/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Mantenimiento mantenimiento)
        {
            try
            {
            if (ModelState.IsValid)
            {
                string path = Server.MapPath("~/Content/Archivos/");
                if (!Directory.Exists(path))
                {
                    Directory.CreateDirectory(path);
                }
                string nombre = path + Path.GetFileName(mantenimiento.Archivo.FileName);
                mantenimiento.Archivo.SaveAs(path + Path.GetFileName(mantenimiento.Archivo.FileName));
                mantenimiento.URLArchivo = nombre;
                db.AgregarMantenimiento(mantenimiento.IdMaquina,mantenimiento.Seccion,mantenimiento.NumeroOperacion,mantenimiento.NombreOperacion,
                    mantenimiento.Frecuencia,mantenimiento.IdRol,mantenimiento.IdUsuario,mantenimiento.IdRepuesto,mantenimiento.Detalles,mantenimiento.URLArchivo);
                db.SaveChanges();
                    db.AgregarBitacora("Mantenimiento", "Crear", "El usuario realiza la acción de crear un Mantenimiento", Convert.ToInt32(Session["IdUsuario"]), DateTime.Now, "crear");
                    @TempData["Message"] = "Se cargaron los archivos";
                return RedirectToAction("Index");
            }
            }
            catch
            {
            ViewBag.IdRepuesto = new SelectList(db.InventarioDeRepuestos, "IdRepuesto", "Nombre", mantenimiento.IdRepuesto);
            ViewBag.IdMaquina = new SelectList(db.Maquina.Where(x => x.Estado == true).ToList(), "IdMaquina", "NombreMaquina", mantenimiento.IdMaquina);
            ViewBag.IdRol = new SelectList(db.Rol, "IdRol", "Descripcion", mantenimiento.Rol);
            
            return View(mantenimiento); 
            }
            ViewBag.IdRepuesto = new SelectList(db.InventarioDeRepuestos, "IdRepuesto", "Nombre", mantenimiento.IdRepuesto);
            ViewBag.IdMaquina = new SelectList(db.Maquina.Where(x => x.Estado == true).ToList(), "IdMaquina", "NombreMaquina", mantenimiento.IdMaquina);
            ViewBag.IdRol = new SelectList(db.Rol, "IdRol", "Descripcion", mantenimiento.Rol);

            return View(mantenimiento);
        }

        // GET: MantenimientoDeMaquinas/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Mantenimiento mantenimientoDeMaquina = db.Mantenimiento.Find(id);

            if (mantenimientoDeMaquina == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdRepuesto = new SelectList(db.InventarioDeRepuestos, "IdRepuesto", "Nombre", mantenimientoDeMaquina.IdRepuesto);
            ViewBag.IdMaquina = new SelectList(db.Maquina.Where(x => x.Estado == true).ToList(), "IdMaquina", "NombreMaquina", mantenimientoDeMaquina.IdMaquina);
            ViewBag.IdRol = new SelectList(db.Rol, "IdRol", "Descripcion", mantenimientoDeMaquina.Rol);
            ViewBag.ListaIdUsuario = CargaUsuario(Convert.ToInt32(mantenimientoDeMaquina.IdUsuario)).ToList();
            return View(mantenimientoDeMaquina);
        }

        // POST: MantenimientoDeMaquinas/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Mantenimiento mantenimientoDeMaquina)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (mantenimientoDeMaquina.Archivo != null)
                    {
                        string path = Server.MapPath("~/Content/Archivos/");
                        string nombre = path + Path.GetFileName(mantenimientoDeMaquina.Archivo.FileName);
                        mantenimientoDeMaquina.Archivo.SaveAs(path + Path.GetFileName(mantenimientoDeMaquina.Archivo.FileName));
                        mantenimientoDeMaquina.URLArchivo = nombre;
                    }
                    db.Entry(mantenimientoDeMaquina).State = EntityState.Modified;
                    db.SaveChanges();
                    db.AgregarBitacora("Mantenimiento", "Editar", "El usuario realiza la acción de editar un Mantenimiento", Convert.ToInt32(Session["IdUsuario"]), DateTime.Now, "editar");
                    @TempData["Message"] = "Se editaron los datos";
                    return RedirectToAction("Index");
                }
            }
            catch
            {
                ViewBag.IdRepuesto = new SelectList(db.InventarioDeRepuestos, "IdRepuesto", "Nombre", mantenimientoDeMaquina.IdRepuesto);
                ViewBag.IdMaquina = new SelectList(db.Maquina.Where(x => x.Estado == true).ToList(), "IdMaquina", "NombreMaquina", mantenimientoDeMaquina.IdMaquina);
                ViewBag.Rol = new SelectList(db.Rol, "IdRol", "Descripcion", mantenimientoDeMaquina.Rol);
                ViewBag.ListaIdUsuario = CargaUsuario(Convert.ToInt32(mantenimientoDeMaquina.IdUsuario)).ToList();
                return View(mantenimientoDeMaquina);
            }
            ViewBag.IdRepuesto = new SelectList(db.InventarioDeRepuestos, "IdRepuesto", "Nombre", mantenimientoDeMaquina.IdRepuesto);
            ViewBag.IdMaquina = new SelectList(db.Maquina.Where(x => x.Estado == true).ToList(), "IdMaquina", "NombreMaquina", mantenimientoDeMaquina.IdMaquina);
            ViewBag.Rol = new SelectList(db.Rol, "IdRol", "Descripcion", mantenimientoDeMaquina.Rol);
            ViewBag.ListaIdUsuario = CargaUsuario(Convert.ToInt32(mantenimientoDeMaquina.IdUsuario)).ToList();
            return View(mantenimientoDeMaquina);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public List<ConsultarUsuariosxRol_Result> CargaUsuario(int IdRol)
        {
            List<ConsultarUsuariosxRol_Result> usuarios = db.ConsultarUsuariosxRol(IdRol).Where(x => x.Estado == true).ToList();
            return usuarios;
        }
        public JsonResult CargaUsuarios(int IdRol)
        {
            List<ConsultarUsuariosxRol_Result> usuarios = db.ConsultarUsuariosxRol(IdRol).Where(x => x.Estado == true).ToList();

            return Json(usuarios, JsonRequestBehavior.AllowGet);
        }
    }
}

ProyectoSMP/Views/MantenimientoDeMaquinas/Create.cshtml
@model ProyectoSMP.Models.Mantenimiento

@{ Layout = "~/Views/Shared/_Layout.cshtml";
                ViewBag.Title = "Create"; }

    @using (Html.BeginForm("Create", "MantenimientoDeMaquinas", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        <h4>Crear Mantenimiento</h4>
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.Hidden("IdMantenimiento", 0)

                        <div class="item form-group">
                            @Html.LabelFor(model => model.IdMaquina, "Máquina", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownList("IdMaquina", null,"Seleccione la Máquina...",htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.IdMaquina, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="item form-group">
                            @Html.LabelFor(model => model.Seccion, "Sección", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Seccion, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Seccion, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="item form-group">
                            @Html.LabelFor(model => model.NumeroOperacion, "Número de Operación", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.NumeroOperacion, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.NumeroOperacion, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="item form-group">
                            @Html.LabelFor(model => model.NombreOperacion, "Nombre de Operación", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.NombreOperacion, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.NombreOperacion, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="item form-group">
                            @Html.LabelFor(model => model.Frecuencia, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Frecuencia, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Frecuencia, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="item form-group">
                            @Html.LabelFor(model => model.IdRol, "Rol", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownListFor(model => model.IdRol, ViewBag.IdRol as SelectList,"Seleccione un Rol...", new { @class = "form-control" })
                            </div>
                        </div>

                        <div class="item form-group">
                            @Html.LabelFor(model => model.IdUsuario, "Usuario", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownListFor(model => model.IdUsuario, new SelectList(" "),"Seleccione un Usuario...", new { @class = "form-control" })
                            </div>
                        </div>

                        <div class="item form-group">
                            @Html.LabelFor(model => model.IdRepuesto, "Repuesto disponible", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownList("IdRepuesto", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.IdRepuesto, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="item form-group">
                            @Html.LabelFor(model => model.Detalles, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Detalles, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Detalles, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="item form-group">
                            @Html.LabelFor(model => model.Archivo, "Manual de Mantenimiento", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.TextBoxFor(m => m.Archivo, new { type = "file" })
                                @Html.ValidationMessageFor(model => model.Archivo, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <hr />
                        <div class="item form-group">
                            <button class="btn btn-outline-dark" type="button">@Html.ActionLink("Regresar", "Index")</button>
                            <input type="submit" value="Crear" class="btn btn-outline-success" />
                        </div>
                    </div>
}
    <hr />
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    @section Scripts
{
        <script type="text/javascript">

    $(document).ready(function () {
        $("#IdRol").change(function () {
            $("#IdUsuario").empty();
            $.ajax({
                type: 'POST',
                url: '@Url.Action("CargaUsuarios")',
                dataType: 'json',
                data: { IdRol: $("#IdRol").val() },
                success: function (usuarios) {
                    $.each(usuarios, function (i, usuario) {
                        $("#IdUsuario").append('<option value="' + usuario.IdUsuario + '">' +
                            usuario.Nombre + " " + usuario.Apellidos + '</option>');

                    });
                },
            })
        });
    });
        </script>
    }

ProyectoSMP/Views/MantenimientoDeMaquinas/Edit.cshtml
@model ProyectoSMP.Models.Mantenimiento

@{ Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Edit"; }

<h2>Editar</h2>

@using (Html.BeginForm("Edit", "MantenimientoDeMaquinas", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
@Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <h4>Mantenimiento</h4>
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.IdMantenimiento)

                    <div class="item form-group">
                        @Html.LabelFor(model => model.IdMaquina, "Máquina", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownList("IdMaquina", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.IdMaquina, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="item form-group">
                        @Html.LabelFor(model => model.Seccion, "Sección", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Seccion, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Seccion, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="item form-group">
                        @Html.LabelFor(model => model.NumeroOperacion, "Número de Operación", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.NumeroOperacion, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.NumeroOperacion, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="item form-group">
                        @Html.LabelFor(model => model.NombreOperacion, "Nombre de Operación", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.NombreOperacion, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.NombreOperacion, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="item form-group">
                        @Html.LabelFor(model => model.Frecuencia, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Frecuencia, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Frecuencia, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="item form-group">
                        @Html.LabelFor(model => model.IdRol, "Rol", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.IdRol, ViewBag.IdRol as SelectList, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.IdRol, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="item form-group">
                        @Html.LabelFor(model => model.IdUsuario, "Usuario", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.IdUsuario, new SelectList(ViewBag.ListaIdUsuario, "IdUsuario", "Nombre"), new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.IdUsuario, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="item form-group">
                        @Html.LabelFor(model => model.IdRepuesto, "Repuesto", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownList("IdRepuesto", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.IdRepuesto, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="item form-group">
                        @Html.LabelFor(model => model.Detalles, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Detalles, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Detalles, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="item form-group">
                        @Html.LabelFor(model => model.Archivo, "Manual de Mantenimiento", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(m => m.Archivo, new { type = "file" })
                            @Html.ValidationMessageFor(model => model.Archivo, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <hr />
                    <div class="item form-group">
                        <div>
                            <button class="btn btn-outline-dark" type="button">@Html.ActionLink("Regresar", "Index")</button>
                        </div>
                        <div>
                            <input type="submit" value="Guardar" class="btn btn-outline-success" />
                        </div>
                    </div>
                </div>}
<script src="~/Scripts/jquery-3.4.1.min.js"></script>
@section Scripts
{
    <script type="text/javascript">

      $(document).ready(function () {
        $("#IdRol").change(function () {
            $("#IdUsuario").empty();
            $.ajax({
                type: 'POST',
                url: '@Url.Action("CargaUsuarios")',
                dataType: 'json',
                data: { IdRol: $("#IdRol").val() },
                success: function (usuarios) {
                    $.each(usuarios, function (i, usuario) {
                        $("#IdUsuario").append('<option value="' + usuario.IdUsuario + '">' +
                            usuario.Nombre + " " + usuario.Apellidos + '</option>');

                    });
                },
            })
        });
    });
    </script>
}

ProyectoSMP/Views/MantenimientoDeMaquinas/Index.cshtml
@model IEnumerable<ProyectoSMP.Models.Mantenimiento>

@{ Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Index"; }
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Lista de Mantenimientos</title>

    <!-- Custom fonts for this template -->
    <link href="~/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="~/css/sb-admin-2.min.css" rel="stylesheet">

    <!-- Custom styles for this page -->
    <link href="~/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet">

</head>
<body id="page-top">
    <div class="container-fluid">
        <h1 class="h3 mb-2 text-gray-800">Lista de Mantenimientos</h1>
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                @if(ViewBag.Message != null)
                {
                    <div class="alert alert-success" role="alert">
                        @ViewBag.Message
                    </div> 
                }
            <h6 class="m-0 font-weight-bold text-primary">
                @Html.ActionLink("Nuevo Mantenimiento", "Create")
            </h6>

            </div>
            <div class="card-body">
                <div class="table-responsive">
                    @Html.ActionLink("Generar reporte", "Print")
                    <hr />
                    <h6>Sí edita un mantenimiento debe volver a ingresar el archivo de Manual de Mantenimiento.</h6>
                    <hr />
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <tr>
                            <th>
                                <h7>Máquina</h7>
                            </th>
                            <th>
                                <h7>Sección</h7>
                            </th>
                            <th>
                                <h7>Número Operación</h7>
                            </th>
                            <th>
                                <h7>Nombre Operación</h7>
                            </th>
                            <th>
                                <h7>Frecuencia</h7>
                            </th>
                            <th>
                                <h7>Rol</h7>
                            </th>
                            <th>
                                <h7>Usuario</h7>
                            </th>
                            <th>
                                <h7>Repuesto</h7>
                            </th>
                            <th>
                                <h7>Detalles</h7>
                            </th>
                            <th>
                                <h7>Manual de Mantenimiento</h7>
                            </th>
                            <th>Acciones</th>
                        </tr>

                        @foreach (var item in Model)
                        {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Maquina.NombreMaquina)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Seccion)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NumeroOperacion)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NombreOperacion)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Frecuencia)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Rol.Descripcion)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Usuario.Nombre)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.InventarioDeRepuestos.Nombre)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Detalles)
                    </td>
                    <td>
                        @if (item.URLArchivo != null)
                        {
                @Html.ActionLink("Ver Archivo", "Descargar", new { id = item.IdMantenimiento }) }
            else
            {
                <h7>No hay Archivo</h7>}

                    </td>
                    <td>
                        @Html.ActionLink("Editar", "Edit", new { id = item.IdMantenimiento })
                    </td>
                </tr>
}

                    </table>
                </div>
            </div>
        </div>
    </div>


    <!-- Bootstrap core JavaScript-->
    <script src="~/vendor/jquery/jquery.min.js"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="~/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/js/sb-admin-2.min.js"></script>

    <!-- Page level plugins -->
    <script src="~/vendor/datatables/jquery.dataTables.min.js"></script>
    <script src="~/vendor/datatables/dataTables.bootstrap4.min.js"></script>

    <!-- Page level custom scripts -->
    <script src="~/js/demo/datatables-demo.js"></script>

</body>

</html>